services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wall
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  # app:
  #   build: .
  #   links:
  #     - db
  #   ports:
  #     - 3000:3000
volumes:
  db_data: